AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template creates an EC2 instance in existing VPC'
Parameters:

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
    
  IpForSSH:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '7'
    MaxLength: '15'
    Default: 0.0.0.0
    #AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    #AllowedPattern: '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
    #ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x
    AllowedPattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
    ConstraintDescription: 'Enter a valid IPv4 address'
    
  NetworkStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC and subnet that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: base-network-stack
    
  EFSStackName:
    Description: >-
      Name of an active CloudFormation stack that contains the EFS
      resources that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: '^[a-zA-Z][-a-zA-Z0-9]*$'
    Default: efs-stack
  
  AttachVolume:
    Description: 'Should the volume be attached?'
    Type: String
    Default: 'yes'
    AllowedValues:
    - 'yes'
    - 'no'
    
Mappings:
  AWSInstanceType2Arch:
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
  AWSInstanceType2NATArch:
    t2.nano:
      Arch: NATHVM64
    t2.micro:
      Arch: NATHVM64
    t2.small:
      Arch: NATHVM64
    t2.medium:
      Arch: NATHVM64
    t2.large:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    eu-west-1:
      HVM64: ami-08935252a36e25f85
      HVMG2: ami-0d5299b1c6112c3c7
    eu-west-2:
      HVM64: ami-01419b804382064e4
      HVMG2: NOT_SUPPORTED
    eu-west-3:
      HVM64: ami-0dd7e7ed60da8fb83
      HVMG2: NOT_SUPPORTED

Conditions:
  Attached: !Equals [!Ref AttachVolume, 'yes']
      
Resources:
  # Add instance profile and role
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
      - !Ref Role
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 
            - 'ec2.amazonaws.com'
          Action: 
          - 'sts:AssumeRole'
      Policies:
      - PolicyName: ec2-volume-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - 'ec2:DescribeVolumes'
            - 'ec2:CreateSnapshot'
            - 'ec2:DescribeSnapshots'
            - 'ec2:DeleteSnapshot'
            Resource: '*'
  EC2InstanceA:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      # Add an already existing role via pre existing instance profile
      # IamInstanceProfile: s3access-profile 
      # Reference an inline instance profile
      IamInstanceProfile: !Ref InstanceProfile 
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref InstanceSecurityGroup
            # EFS Client Security Group Config
            - Fn::ImportValue: !Sub ${EFSStackName}-efsclientsg
          SubnetId:
            Fn::ImportValue:
              !Sub ${NetworkStackName}-publicsubnet-az1
      UserData:
        Fn::Base64: 
          Fn::Sub: 
          - |
            #!/bin/bash -x
            bash -ex << "TRY"
              # wait until EFS file system is available
              while ! nc -z ${EfsFileSystemId}.efs.${AWS::Region}.amazonaws.com 2049; do sleep 10; done
              sleep 10

              # copy existing /home to /oldhome
              mkdir /oldhome
              cp -a /home/. /oldhome

              # mount EFS file system
              echo "${EfsFileSystemId}.efs.${AWS::Region}.amazonaws.com:/ /home nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab
              mount -a

              # copy /oldhome to new /home
              cp -a /oldhome/. /home
            TRY
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2InstanceA --region ${AWS::Region}
          - EfsFileSystemId:
              Fn::ImportValue:
                !Sub "${EFSStackName}-filesystem"
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-ec2-instance-a" ]]
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
  EC2InstanceB:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      # Add an already existing role via pre existing instance profile
      # IamInstanceProfile: s3access-profile 
      # Reference an inline instance profile
      IamInstanceProfile: !Ref InstanceProfile 
      KeyName: !Ref KeyName
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap 
          - AWSInstanceType2Arch
          - !Ref InstanceType
          - Arch
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet: 
            - !Ref InstanceSecurityGroup
            # EFS Client Security Group Config
            - Fn::ImportValue: !Sub ${EFSStackName}-efsclientsg
          SubnetId:
            Fn::ImportValue:
              !Sub ${NetworkStackName}-publicsubnet-az2
      UserData:
        Fn::Base64: 
          Fn::Sub: 
          - |
            #!/bin/bash -x
            bash -ex << "TRY"
              # wait until EFS file system is available
              while ! nc -z ${EfsFileSystemId}.efs.${AWS::Region}.amazonaws.com 2049; do sleep 10; done
              sleep 10

              # mount EFS file system
              echo "${EfsFileSystemId}.efs.${AWS::Region}.amazonaws.com:/ /home nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev 0 0" >> /etc/fstab
              mount -a
              
            TRY
            /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2InstanceB --region ${AWS::Region}
          - EfsFileSystemId:
              Fn::ImportValue:
                !Sub "${EFSStackName}-filesystem"
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-ec2-instance-b" ]]
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M  
  VolumeA:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !Sub ${EC2InstanceA.AvailabilityZone}
      Size: 5
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: 'ian-volume-a'
  VolumeAttachmentA:
    Type: 'AWS::EC2::VolumeAttachment'
    Condition: Attached
    Properties:
      Device: '/dev/xvdf'
      InstanceId: !Ref EC2InstanceA
      VolumeId: !Ref VolumeA
  VolumeB:
    Type: 'AWS::EC2::Volume'
    Properties:
      AvailabilityZone: !Sub ${EC2InstanceB.AvailabilityZone}
      Size: 5
      VolumeType: gp2
      Tags:
      - Key: Name
        Value: 'ian-volume-b'
  VolumeAttachmentB:
    Type: 'AWS::EC2::VolumeAttachment'
    Condition: Attached
    Properties:
      Device: '/dev/xvdf'
      InstanceId: !Ref EC2InstanceB
      VolumeId: !Ref VolumeB
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allowing incoming SSH and ICPM from source'
      VpcId:
        Fn::ImportValue:
          !Sub ${NetworkStackName}-vpc
      SecurityGroupIngress:
      - IpProtocol: icmp
        FromPort: "-1"
        ToPort: "-1"
        CidrIp: !Sub '${IpForSSH}/32'
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Sub '${IpForSSH}/32'
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
      Tags:
      - Key: Name
        Value: !Join ['', [!Ref "AWS::StackName", "-ec2-instance-sg" ]]
        
Outputs:
  InstanceIdA:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2InstanceA
  AZA:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceA
      - AvailabilityZone
  PublicDNSA:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceA
      - PublicDnsName
  PublicIPA:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceA
      - PublicIp
  VolumeIdA:
    Value: !Ref VolumeA
    Description: 'ID of the EBS volume'
  InstanceIdB:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref EC2InstanceB
  AZB:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceB
      - AvailabilityZone
  PublicDNSB:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceB
      - PublicDnsName
  PublicIPB:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 
      - EC2InstanceB
      - PublicIp
  VolumeIdB:
    Value: !Ref VolumeB
    Description: 'ID of the EBS volume'