AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create a basic VPC'
Parameters:
  vpccidrblock:
    Description: 'VPC CIDR block range'
    Type: String
    
  publicsubnetaz1cidrblock:
    Description: 'Public Subnet AZ1 CIDR block range'
    Type: String
    
  publicsubnetaz2cidrblock:
    Description: 'Public Subnet AZ2 CIDR block range'
    Type: String
    
  IpForSSH:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '7'
    MaxLength: '15'
    Default: 89.101.127.157
    #AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    #AllowedPattern: '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'
    #ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x
    AllowedPattern: '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
    ConstraintDescription: 'Enter a valid IPv4 address'
    
Resources:
  VPCConfig:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        !Ref vpccidrblock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-vpc" ]]
  # VPC requires internet access:     
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPCConfig
    Properties:
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-igw" ]]
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    # Attach gateway to VPC
    Properties:
      VpcId: !Ref VPCConfig
      InternetGatewayId: !Ref InternetGateway
  # Add Subnets
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCConfig
      CidrBlock: 
        !Ref publicsubnetaz1cidrblock
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-publicsubnet-az1
  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPCConfig
      CidrBlock: 
        !Ref publicsubnetaz2cidrblock
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-publicsubnet-az2
  # Public Route tables for public subnets:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCConfig
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-rt
  PublicRoute1:   # Public route table has direct routing to IGW:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  # Attach the public subnets to public route tables,
  PublicSubnetARouteTableAssociationAz1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetARouteTableAssociationAz2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable
  # Add NACLs
  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPCConfig
  SubnetNetworkAclAssociationA:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      NetworkAclId: !Ref NetworkAcl
  SubnetNetworkAclAssociationB:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      NetworkAclId: !Ref NetworkAcl
  NetworkAclEntryIngress:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref NetworkAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: false
      CidrBlock: !Sub '${IpForSSH}/32'
  NetworkAclEntryEgress:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref NetworkAcl
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      Egress: true
      CidrBlock: !Sub '${IpForSSH}/32'
Outputs:
  StackVPC:
    Description: The name of the VPC
    Value: !Ref VPCConfig
    Export: 
      Name: !Sub "${AWS::StackName}-vpc"
  PublicSubnetAZ1:
    Description: The ID of the Public Subnet in AZ1
    Value: !Ref PublicSubnetAZ1
    Export: 
      Name: !Sub "${AWS::StackName}-publicsubnet-az1"
  PublicSubnetAZ2:
    Description: The ID of the Public Subnet in AZ2
    Value: !Ref PublicSubnetAZ2
    Export: 
      Name: !Sub "${AWS::StackName}-publicsubnet-az2"