AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create a basic S3 Bucket'
Parameters:
  bucketname:
    Description: 'S3 Bucket Name'
    Type: String
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref bucketname