AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation template to create a VPC with IGW and Public / Private Subnets'
Parameters:
  vpccidrblock:
    Description: 'VPC CIDR block range'
    Type: String
  publicsubnetaz1cidrblock:
    Description: 'Public Subnet AZ1 CIDR block range'
    Type: String
  publicsubnetaz2cidrblock:
    Description: 'Public Subnet AZ2 CIDR block range'
    Type: String
  privatesubnetaz1cidrblock:
    Description: 'Prvate Subnet AZ1 CIDR block range'
    Type: String
  privatesubnetaz2cidrblock:
    Description: 'Private Subnet AZ2 CIDR block range'
    Type: String
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 
        !Ref vpccidrblock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-vpc" ]]
  # VPC requires internet access:     
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-igw" ]]
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    # Attach gateway to VPC
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  # Add Subnets
  PublicSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 
        !Ref publicsubnetaz1cidrblock
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-az1-subnet
  PublicSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 
        !Ref publicsubnetaz2cidrblock
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-az2-subnet
  PrivateSubnetAZ1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock:
        !Ref privatesubnetaz1cidrblock
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-private-az1-subnet
  PrivateSubnetAZ2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock:
        !Ref privatesubnetaz2cidrblock
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-private-az2-subnet
  # Public Route tables for public subnets:
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-public-routetable
  PublicRoute1:   # Public route table has direct routing to IGW:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  ElasticIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC 
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetAZ2
      RouteTableId: !Ref PublicRouteTable
Outputs:
  StackVPC:
    Description: The ID of the VPC
    Value: !Ref VPC
    Export: 
      Name: !Sub "${AWS::StackName}-VPCID"
  PublicSubnetAZ1:
    Description: The ID of the Public Subnet in AZ1
    Value: !Ref PublicSubnetAZ1
    Export: 
      Name: !Sub "${AWS::StackName}-PUBSUBAZ1"
  PublicSubnetAZ2:
    Description: The ID of the Public Subnet in AZ2
    Value: !Ref PublicSubnetAZ2
    Export: 
      Name: !Sub "${AWS::StackName}-PUBSUBAZ2"
  PrivateSubnetAZ1:
    Description: The ID of the Private Subnet in AZ1
    Value: !Ref PrivateSubnetAZ1
    Export: 
      Name: !Sub "${AWS::StackName}-PRIVSUBAZ1"
  PrivateSubnetAZ2:
    Description: The ID of the Private Subnet in AZ2
    Value: !Ref PrivateSubnetAZ2
    Export: 
      Name: !Sub "${AWS::StackName}-PRIVSUBAZ2"